### ISSUE TITLE
RMSD not shown tm_align function.

### ISSUE THREAD

**Issue by profdocpizza** [jvkersch/tmtools#19]
Would be great if along with rotation matrix, translation vector, and tm score, RMSD would be also an output of tm_align function

**Comment by jvkersch** [comment]
@profdocpizza If the original TMalign software computes it, then it would be easy to expose. I'm not in front of my laptop right now, do you know if TMalign computes RMSD?

**Comment by cvigilv** [comment]
Hi! 

Bumping this stale issue, since I need this output also. 

TMalign does provide RMSD as an output. I have been tinkering but haven't been able to see how to access this information. 

Could you guide me how to expose things with pybind11 to expose the complete output of TMalign?

Thanks in advance!

**Comment by jvkersch** [comment]
> Could you guide me how to expose things with pybind11 to expose the complete output of TMalign?

I saw you created a PR with fixes to the pybind11 code, is this still an issue?

**Comment by cvigilv** [comment]
With the PR this is no longer an issue
