### ISSUE TITLE
IPython kernel dies when encountering errors within `.cpp` code 

### ISSUE THREAD

**Issue by kamurani** [jvkersch/tmtools#27]
For example, providing sequences that are below the minimum length (as defined within the original source code): 

```python
import numpy as np
from tmtools import tm_align

coords1 = np.array(
     [[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
coords2 = np.array(
    [[0,0,0],[1,1,1]])
seq1 = "AAAA" 
seq2 = "CC"
tm_align(coords1, coords2, seq1, seq2)
```
Produces the following: 
```ipython
The Kernel crashed while executing code in the current cell or a previous cell. 

Please review the code in the cell(s) to identify a possible cause of the failure. 

Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. 

View Jupyter [log](command:jupyter.viewOutput) for further details.
```

Expected output: A python `ValueError` should be raised, as this is more interpretable than the kernel dying.

**Comment by jvkersch** [comment]
@kamurani Thank you for flagging this, this is an extremely important bug to fix. However, I think it should be fixed on the level of the C++ code, not in Python, since there are many code paths that call `exit()` in the C++ code and guarding against all of them would be prohibitive. One way to do so is to raise a C++ error instead of exiting directly; I've pushed a fix along those lines in #29. Could you have a look to see if that fix works for you?

One issue with raising a generic `std::runtime_error` is that it doesn't differentiate between the different kinds of exceptions. It would be nicer that a `ValueError` is raised when mismatching inputs are passed in, like in your MWE. But doing this would require more substantial changes to the C++ code (custom exceptions + handling on the Python side). That could be worth doing but I'd first like to see this bug fixed.
