### ISSUE TITLE
Implement function to translate/rotate protein based on TMResult

### ISSUE THREAD

**Issue by cvigilv** [jvkersch/tmtools#35]
Hi again! Using the package I noticed that there is no exposed function that allows the user to transform a protein based on the results of the TMAlign algorithm. Since the `TMResult` object provvides the rotation and translation matrices, one can use this information to obtain the rotated/translated protein that one aligned previously. I have a prototype, would you be willing to accept a PR to implement this functionality or is it outside the scope of the package?

**Comment by jvkersch** [comment]
@cvigilv Yes, this would be a good idea, I think. Feel free to open a PR with your prototype, we can have a look.

Funny thing, at first my reaction was that we wouldn't need this, since the coordinate matrices, rotation matrix and translation vectors are all NumPy arrays, so that it would be trivial to effect the desired transformation. And then I spent a good 10 minutes trying to figure out whether to multiply by the right or left, whether the transformation goes from protein 1 to 2 or the other way round, and so on.

**Comment by cvigilv** [comment]
Linked to #39
